version: '3.8'

services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
  baice-api:
    build:
      context: .
    command: npm run start:dev
    env_file: .env
    volumes:
      - .:/usr/app
    ports:
      - 9000:9000
    depends_on:
      - mongo
  baice-api-prd:
    build:
      context: .
    command: npm run start
    env_file: .env
    ports:
      - 9000:9000
    depends_on:
      - mongo
  test:
    build:
      context: .
    command: npm test
    env_file: .env
    volumes:
      - .:/usr/app
    ports:
      - 9000:9000
    depends_on:
      - mongo
